import "./CardBackside.css";
import "../../main.css";

export const CardBackside = () => {
  return (
    <div className="card-base card-backside center">
      <div className="card-backside-inner">
        <div className="backside-pattern-container">
          <svg className="backside-pattern" viewBox="0 0 400 400">
            <defs>
              <pattern
                id="bg_pattern"
                width="100"
                height="100"
                patternUnits="userSpaceOnUse"
              >
                <circle
                  cx="15"
                  cy="15"
                  r="20"
                  fill="none"
                  stroke="#cf009b"
                  strokeWidth="6"
                  opacity="0.8"
                ></circle>{" "}
                <circle
                  cx="85"
                  cy="15"
                  r="20"
                  fill="none"
                  stroke="#cf009b"
                  strokeWidth="6"
                  opacity="0.8"
                ></circle>{" "}
                <circle
                  cx="15"
                  cy="85"
                  r="20"
                  fill="none"
                  stroke="#cf009b"
                  strokeWidth="6"
                  opacity="0.8"
                ></circle>
                <circle
                  cx="85"
                  cy="85"
                  r="20"
                  fill="none"
                  stroke="#cf009b"
                  strokeWidth="6"
                  opacity="0.8"
                ></circle>{" "}
                <line
                  x1="80"
                  y1="80"
                  x2="90"
                  y2="90"
                  stroke="#ff2370"
                  strokeWidth="6"
                  strokeLinecap="round"
                  opacity="0.8"
                ></line>{" "}
                <line
                  x1="10"
                  y1="10"
                  x2="20"
                  y2="20"
                  stroke="#ff2370"
                  strokeWidth="6"
                  strokeLinecap="round"
                  opacity="0.8"
                ></line>{" "}
                <line
                  x1="80"
                  y1="20"
                  x2="90"
                  y2="10"
                  stroke="#ff2370"
                  strokeWidth="6"
                  strokeLinecap="round"
                  opacity="0.8"
                ></line>{" "}
                <line
                  x1="20"
                  y1="80"
                  x2="10"
                  y2="90"
                  stroke="#ff2370"
                  strokeWidth="6"
                  strokeLinecap="round"
                  opacity="0.8"
                ></line>
                <circle
                  cx="50"
                  cy="50"
                  r="10"
                  fill="#ff794e"
                  opacity="0.8"
                ></circle>
              </pattern>
            </defs>
            <rect
              x="0"
              y="0"
              width="100%"
              height="100%"
              fill="#f9f9ff"
              opacity="0.4"
            ></rect>
            <rect
              x="0"
              y="0"
              width="100%"
              height="100%"
              fill="url(#bg_pattern)"
              opacity="0.8"
            ></rect>
          </svg>
          <svg className="backside-pattern" viewBox="0 0 400 400">
            <defs>
              <pattern
                id="bg_pattern"
                width="100"
                height="100"
                patternUnits="userSpaceOnUse"
              >
                <circle
                  cx="15"
                  cy="15"
                  r="20"
                  fill="none"
                  stroke="#591dc0"
                  strokeWidth="6"
                  opacity="0.8"
                ></circle>{" "}
                <circle
                  cx="85"
                  cy="15"
                  r="20"
                  fill="none"
                  stroke="#591dc0"
                  strokeWidth="6"
                  opacity="0.8"
                ></circle>{" "}
                <circle
                  cx="15"
                  cy="85"
                  r="20"
                  fill="none"
                  stroke="#cf009b"
                  strokeWidth="6"
                  opacity="0.8"
                ></circle>
                <circle
                  cx="85"
                  cy="85"
                  r="20"
                  fill="none"
                  stroke="#591dc0"
                  strokeWidth="6"
                  opacity="0.8"
                ></circle>{" "}
                <line
                  x1="80"
                  y1="80"
                  x2="90"
                  y2="90"
                  stroke="#ff2370"
                  strokeWidth="6"
                  strokeLinecap="round"
                  opacity="0.8"
                ></line>{" "}
                <line
                  x1="10"
                  y1="10"
                  x2="20"
                  y2="20"
                  stroke="#ff2370"
                  strokeWidth="6"
                  strokeLinecap="round"
                  opacity="0.8"
                ></line>{" "}
                <line
                  x1="80"
                  y1="20"
                  x2="90"
                  y2="10"
                  stroke="#ff2370"
                  strokeWidth="6"
                  strokeLinecap="round"
                  opacity="0.8"
                ></line>{" "}
                <line
                  x1="20"
                  y1="80"
                  x2="10"
                  y2="90"
                  stroke="#ff2370"
                  strokeWidth="6"
                  strokeLinecap="round"
                  opacity="0.8"
                ></line>
                <circle
                  cx="50"
                  cy="50"
                  r="10"
                  fill="#ff794e"
                  opacity="0.8"
                ></circle>
              </pattern>
            </defs>
            <rect
              x="0"
              y="0"
              width="100%"
              height="100%"
              fill="#f9f9ff"
              opacity="0.4"
            ></rect>
            <rect
              x="0"
              y="0"
              width="100%"
              height="100%"
              fill="url(#bg_pattern)"
              opacity="0.8"
            ></rect>
          </svg>
        </div>
      </div>
    </div>
  );
};
